development:
  adapter: sqlite
  pool: 5
  timeout: 3000
  database: data/scrabble_scorer_core_development.sqlite3

test:
  adapter: sqlite
  pool: 5
  timeout: 3000
  database: data/scrabble_scorer_core_test.sqlite3

production:
  adapter: sqlite
  pool: 5
  timeout: 3000
  database: data/scrabble_scorer_core_production.sqlite3
